name: doctions

on:
  workflow_call:
    inputs:
      workflow-file:
        description: Path to doctions workflow YAML file
        default: data/workflows/release.yml
        required: false
        type: string
      contexts-file:
        description: Path to doctions contexts YAML file
        required: true
        type: string
      display-step-summary:
        description: Set to any value to have the markdown displayed as a step summary
        required: false
        default: ''
        type: string
    outputs:
      markdown:
        description: Rendered markdown text
        value: ${{ jobs.render.outputs.markdown }}

env:
  PIP_PROGRESS_BAR: "off"

jobs:
  render:
    name: doctions run (${{ inputs.workflow-file }}/${{ inputs.contexts-file }})
    runs-on: ubuntu-latest
    outputs:
      markdown: ${{ steps.set-outputs.markdown }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install doctions
        run:
          pip install tools/doctions
      - name: Run doctions
        run: |
          doctions run \
          --renderer md \
          --output-path ./doctions-output \
          --contexts "${{ inputs.contexts-file }}" \
          "${{ inputs.workflow-file }}"
      - name: Set outputs
        id: set-outputs
        run: |
          echo "markdown=$(cat ./doctions-output/workflow.md)" >> $GITHUB_OUTPUT
      - name: Display generated Markdown as step summary
        if: ${{ inputs.display-step-summary }}
        run: |
          cp ./doctions-output/workflow.md $GITHUB_STEP_SUMMARY
