name: doctions

on:
  push:

env:
  PIP_PROGRESS_BAR: "off"

jobs:
  render:
    name: doctions render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install doctions
        run:
          pip install tools/doctions
      - name: Run doctions
        run:
          doctions --help
