name: Release idaes-ui
run-name: Release idaes-ui${{ inputs.tag }}

on:
  workflow_dispatch:
    inputs:

      tag:
        description: Version tag
        type: string
        required: true

      phase:
        description: Which phase of the release process to run
        type: choice
        required: true
        options:
          - pypi

jobs:

  pypi:
    name: Create PyPI package for idaes-ui ${{ inputs.tag }}
    if: inputs.phase == 'pypi'
    uses: ./.github/workflows/pypi.yml
    with:
      upload: true
      repository: IDAES/idaes-ui
      release-tag: ${{ inputs.tag }}
      pypi-name: idaes-ui
      python-version: '3.11'
      runner-image: ubuntu-22.04
      build-command: |
        python -m build
      test-command: |
        python -c 'from importlib.metadata import version; print(version("idaes-ui"))'
    secrets:
      test-pypi-token: ${{ secrets.TESTPYPI_TOKEN_LBIANCHI }}
      pypi-token: ${{ secrets.PYPI_TOKEN_LBIANCHI }}

  env-snapshot:
    name: Create env snapshot for idaes-ui ${{ inputs.tag }}
    needs: [pypi]
    uses: ./.github/workflows/env-snapshot.yml
    with:
      pypi-name: idaes-ui
      version: ${{ inputs.tag }}
      pip-install-target: "idaes-ui==${{ inputs.tag }}" idaes-pse
      python-version: '3.11'