name: Release watertap
run-name: Release watertap ${{ inputs.tag }}

on:
  workflow_dispatch:
    inputs:

      tag:
        description: Version tag
        type: string
        required: true

      phase:
        description: Which phase of the release process to run
        type: choice
        required: true
        options:
          - pypi

jobs:

  pypi:
    name: Create PyPI package for watertap ${{ inputs.tag }}
    if: inputs.phase == 'pypi'
    uses: ./.github/workflows/pypi.yml
    with:
      upload: true
      repository: watertap-org/watertap
      release-tag: ${{ inputs.tag }}
      pypi-name: watertap
      python-version: '3.11'
      build-command: |
        python -m build
      test-command: |
        idaes get-extensions --extra petsc --verbose
        pip install pytest
        pytest --pyargs watertap -m "unit" -x
    secrets:
      test-pypi-token: ${{ secrets.TESTPYPI_TOKEN_LBIANCHI }}
      pypi-token: ${{ secrets.PYPI_TOKEN_LBIANCHI }}

  env-snapshot:
    name: Create env snapshot for watertap ${{ inputs.tag }}
    needs: [pypi]
    uses: ./.github/workflows/env-snapshot.yml
    with:
      pypi-name: watertap
      version: ${{ inputs.tag }}
      extras-require: '[oli_api,notebooks]'
      python-version: '3.11'