name: Release idaes-examples
run-name: Release idaes-examples ${{ inputs.tag }}

on:
  workflow_dispatch:
    inputs:

      tag:
        description: Version tag
        type: string
        required: true

      phase:
        description: Which phase of the release process to run
        type: choice
        required: true
        options:
          - pypi
          - env-snapshot

jobs:

  pypi:
    name: Create PyPI package for idaes-examples${{ inputs.tag }}
    if: inputs.phase == 'pypi'
    uses: ./.github/workflows/pypi.yml
    with:
      upload: true
      repository: IDAES/examples
      release-tag: ${{ inputs.tag }}
      pypi-name: idaes-examples
      python-version: '3.11'
      build-command: |
        # we specify --wheel because the package size is large enough (71M)
        # that the default behavior of building sdist + wheel would push it past the PyPI 100M maximum
        python -m build --wheel
      test-command: |
        python -c 'from importlib.metadata import version; print(version("idaes-examples"))'
    secrets:
      test-pypi-token: ${{ secrets.TESTPYPI_TOKEN_LBIANCHI }}
      pypi-token: ${{ secrets.PYPI_TOKEN_LBIANCHI }}

  env-snapshot:
    name: Create env snapshot for idaes-examples ${{ inputs.tag }}
    if: inputs.phase == 'env-snapshot'
    uses: ./.github/workflows/env-snapshot.yml
    with:
      pypi-name: idaes-examples
      version: ${{ inputs.tag }}
      extras-require: '[idaes,omlt]'
      python-version: '3.11'