name: Test PyPI workflow

on:

  workflow_dispatch:
    inputs:

      target:
        description: Target to use for PyPI workflow
        type: choice
        required: true
        options:
          - ccsi-foqus
          - idaes-pse
          # - idaes-examples
          # - idaes-ui
          # - pareto
          # - prommis
          # - watertap

      release-tag:
        description: Release tag to be used
        type: string
        required: true

jobs:

  test-no-upload:
    name: Test PyPI for `${{ inputs.target }}` (no upload)
    strategy:
      fail-fast: true
      matrix:
        target:
          - ${{ inputs.target }}
        include:

          - target: ccsi-foqus
            repository: CCSI-Toolset/FOQUS
            pypi-name: ccsi-foqus
            test-command: |
              foqus --help
            python-version: '3.11'
            build-command: |
              rm -r examples/ && python setup.py sdist bdist_wheel

          - target: idaes-pse
            repository: IDAES/idaes-pse
            pypi-name: idaes-pse
            test-command: |
              idaes get-extensions --extra petsc --verbose
              pip install pytest
              wget https://raw.githubusercontent.com/IDAES/idaes-pse/main/pytest.ini
              pytest --pyargs idaes -m "unit" -x
            python-version: '3.11'
            build-command: |
              python setup.py sdist bdist_wheel

    uses: ./.github/workflows/pypi.yml
    with:
      repository: ${{ matrix.repository }}
      release-tag: ${{ inputs.release-tag }}
      pypi-name: ${{ matrix.pypi-name }}
      python-version: ${{ matrix.python-version }}
      build-command: ${{ matrix.build-command }}
      test-command: ${{ matrix.test-command }}
    secrets:
      test-pypi-token: ''
      pypi-token: ''
