name: Test PyPI workflow
run-name: Test PyPI workflow

on:

  workflow_dispatch:
  push:
    files:
      - .github/workflows/pypi.yml
      - .github/workflows/test-pypi.yml

jobs:

  test-all:
    name: Test env snapshot for ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - target: ccsi-foqus
            upload: false
            release-tag: '3.21.0'
            repository: CCSI-Toolset/FOQUS
            pypi-name: ccsi-foqus
            python-version: '3.11'
            test-command: |
              foqus --help
            build-command: |
              rm -r examples/ && python setup.py sdist bdist_wheel

          - target: idaes-pse
            upload: false
            repository: IDAES/idaes-pse
            release-tag: '2.5.0'
            pypi-name: idaes-pse
            python-version: '3.10'
            extras-require: '[ui,coolprop,grid,omlt]'
            test-command: |
              idaes get-extensions --extra petsc --verbose
              pip install pytest
              wget https://raw.githubusercontent.com/IDAES/idaes-pse/main/pytest.ini
              pytest --pyargs idaes -m "unit" -x
            build-command: |
              python setup.py sdist bdist_wheel

    uses: ./.github/workflows/pypi.yml
    with:
      upload: ${{ matrix.upload }}
      repository: ${{ matrix.repository }}
      pypi-name: ${{ matrix.pypi-name }}
      release-tag: ${{ matrix.release-tag }}
      python-version: ${{ matrix.python-version }}
      build-command: ${{ matrix.build-command }}
      extras-require: ${{ matrix.extras-require }}
      test-command: ${{ matrix.test-command }}
